### ISSUE TITLE
Please help AntDesign Blazor for the mentions

### ISSUE THREAD

**Issue by ElderJames** [drocha87/blazorServerMentions#4]
This is a great project, can you help with AntDesign Mentions components?

**Comment by drocha87** [comment]
@ElderJames this project was just an experimentation in creating a mention textarea to MudBlazor. 

AFAIK blazor ant design has a [mention textarea](https://antblazor.com/en-US/components/mentions) already implemented, have you tried it?  

As I said this was just an experiment, I'm not interested in keep working on this project, sorry about that, feel free to fork and port it to ant design. If you need some help understanding some piece of the code, feel free to ask me. 

If I can help you with something else, let me know!

**Comment by drocha87** [comment]
@ElderJames how are you? I answered your question before, but I misread it, so I deleted my previous answer, sorry about that. 

I'll take a look to your project, to be fair I never used ant design so I'm not that familiarized with your code base.

As soon as I have some free time I can take a look at the repo, I guess I should start [here](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/mentions) right?

**Comment by ElderJames** [comment]
Thank you for your willingness to help @drocha87 . 

The mentions in AntDeisgn Blazor don't work, so when I see this project, I'm happy to see that someone has implemented that feature.

We've implemented dropdown, which might help you a little bit as you get closer to implementing this feature for Ant Design Blazor.

> As soon as I have some free time I can take a look at the repo, I guess I should start [here](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/mentions) right?

Yes, here is where the mentions place.

JS is located in the [here](https://github.com/ant-design-blazor/ant-design-blazor/tree/master/components/core/JsInterop) .

The build steps are also on [readme](https://github.com/ant-design-blazor/ant-design-blazor#local).

We look forward to your contribution! Thank you.

Best Regards
